### PR TITLE
gitignore fix to allow ignore files after fork/clone. Camera precise module

### PR DESCRIPTION
**Pull request by Nikzed**
Hey! The code style for Dart was used 120 symbols in line length.
image
Please let me know settings you are using for this project if it's required for this pull request to be accepted.

The main changes are:

- Added support for .gitignore. It was not working before
- Allow user to choose camera module on opening (_CameraDevice rear/front_)

### CODE REVIEW

**Comment by rafidgotit** [comment]
I am using 200 chars as I use bigger monitor :3

**Comment by Nikzed** [comment]
> I am using 200 chars as I use bigger monitor :3

Good to be you)

Updated in the last commit ❤️

**Comment by rafidgotit** [comment]
Thank you for contributing, 
small change, yet means a lot...

**Comment by Nikzed** [comment]
> Thank you for contributing, small change, yet means a lot...

Hey! thank you very much for encouraging, I will upload next commit asap, I wanted to ask what do you think about adding camera preview as a new feature, thanks

**Pull request merged**
